module.exports = {
    provinceGeo: {
        '上海市': 'https://geo.datav.aliyun.com/areas/bound/310000_full.json',
        '云南省': 'https://geo.datav.aliyun.com/areas/bound/530000_full.json',
        '内蒙古自治区': 'https://geo.datav.aliyun.com/areas/bound/150000_full.json',
        '北京市': 'https://geo.datav.aliyun.com/areas/bound/110000_full.json',
        '台湾省': 'https://geo.datav.aliyun.com/areas/bound/710000_full.json',
        '吉林省': 'https://geo.datav.aliyun.com/areas/bound/220000_full.json',
        '四川省': 'https://geo.datav.aliyun.com/areas/bound/510000_full.json',
        '天津市': 'https://geo.datav.aliyun.com/areas/bound/120000_full.json',
        '宁夏回族自治区': 'https://geo.datav.aliyun.com/areas/bound/640000_full.json',
        '安徽省': 'https://geo.datav.aliyun.com/areas/bound/340000_full.json',
        '山东省': 'https://geo.datav.aliyun.com/areas/bound/370000_full.json',
        '山西省': 'https://geo.datav.aliyun.com/areas/bound/140000_full.json',
        '广东省': 'https://geo.datav.aliyun.com/areas/bound/440000_full.json',
        '广西壮族自治区': 'https://geo.datav.aliyun.com/areas/bound/450000_full.json',
        '新疆维吾尔自治区': 'https://geo.datav.aliyun.com/areas/bound/650000_full.json',
        '江苏省': 'https://geo.datav.aliyun.com/areas/bound/320000_full.json',
        '江西省': 'https://geo.datav.aliyun.com/areas/bound/360000_full.json',
        '河北省': 'https://geo.datav.aliyun.com/areas/bound/130000_full.json',
        '河南省': 'https://geo.datav.aliyun.com/areas/bound/410000_full.json',
        '浙江省': 'https://geo.datav.aliyun.com/areas/bound/330000_full.json',
        '海南省': 'https://geo.datav.aliyun.com/areas/bound/460000_full.json',
        '湖北省': 'https://geo.datav.aliyun.com/areas/bound/420000_full.json',
        '湖南省': 'https://geo.datav.aliyun.com/areas/bound/430000_full.json',
        '澳门特别行政区': 'https://geo.datav.aliyun.com/areas/bound/820000_full.json',
        '甘肃省': 'https://geo.datav.aliyun.com/areas/bound/620000_full.json',
        '福建省': 'https://geo.datav.aliyun.com/areas/bound/350000_full.json',
        '西藏自治区': 'https://geo.datav.aliyun.com/areas/bound/540000_full.json',
        '贵州省': 'https://geo.datav.aliyun.com/areas/bound/520000_full.json',
        '辽宁省': 'https://geo.datav.aliyun.com/areas/bound/210000_full.json',
        '重庆市': 'https://geo.datav.aliyun.com/areas/bound/500000_full.json',
        '陕西省': 'https://geo.datav.aliyun.com/areas/bound/610000_full.json',
        '青海省': 'https://geo.datav.aliyun.com/areas/bound/630000_full.json',
        '香港特别行政区': 'https://geo.datav.aliyun.com/areas/bound/810000_full.json',
        '黑龙江省': 'https://geo.datav.aliyun.com/areas/bound/230000_full.json',
    }
}